### ISSUE TITLE
State of FAN

### ISSUE THREAD

**Issue by deon-wentzel** [rgavril/homebridge-mqtt-fan-tasmota#1]
Hi, The plugin works well. I only have one issue and that is when homebridge restarts the Home App shows the FAN is off even though it is on. It would be great if the plugin recognises the state of the FAN, similar to homebridge-mqtt-switch-tasmota.

**Comment by rgavril** [comment]
FIxed in version 0.0.4, you can update.

**Comment by deon-wentzel** [comment]
Thanks, I will test and if any issues I will revert back .
