### ISSUE TITLE
State of FAN when power is off

### ISSUE THREAD

**Issue by deon-wentzel** [rgavril/homebridge-mqtt-fan-tasmota#2]
Hi,

So when the FAN power is off the HOME Apps and Hombridge Configuration UI still shows the FAN as active, instead of No Response. Will you be able to fix this?

**Comment by rgavril** [comment]
I've managed the make a change so the status of the fan is set to 'No Response' when the power is off. 

It will be changed to 'No Response' when the mqtt broker notifies that the device is no longer available (Ex: tele/sonoff-ifan02/LWT Offline) and back to normal after the Online notification.

Note that there is a slight delay until Home app shows the device status. You can force to show by controlling the fan or reloading the Home app.
